### ISSUE TITLE
Different tx_index value across different API services

### ISSUE THREAD

**Issue by wileyj** [hirosystems/stacks-blockchain-api#1004] opened 2022-01-25 17:45 UTC
**Describe the bug**
Retrieving a block hash across different API nodes can result in different `tx_index` values for the transactions
Related: https://github.com/stacks-network/stacks-blockchain/pull/2906

**To Reproduce**
query a blockhash, like:
https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/block/0xfa7b09b77e8a8445f7447da8eb4c410ff16fb58468ea06832076245c4f0e2a8a

and compare to another API node:
http://3.90.87.225/extended/v1/tx/block/0xfa7b09b77e8a8445f7447da8eb4c410ff16fb58468ea06832076245c4f0e2a8a

**Expected behavior**
The output is expected to be identical, but as you can see the tx's are ordered differently across the different API services. 
The data is identical, but the order is different.

**Comment by wileyj** [comment] 2022-02-01 18:10
ping - any update on when a fix might be merged here?

**Comment by diwakergupta** [comment] 2022-02-01 18:20
> ping - any update on when a fix might be merged here?

@wileyj can you characterize how this is impacting you? that'll help us figure out the priority (cc/ @saralab )

Meanwhile, I suspect this might actually get fixed by #662  (@zone117x can you confirm?). Also note that the root cause is actually behavior within stacks-blockchain (see stacks-network/stacks-blockchain#2906 which looks merged)

**Comment by zone117x** [comment] 2022-02-02 14:01
So there's two issues. One is related to tx_index being incorrect and possibly nondeterministic in certain cases (usually involving microblocks). That issue will be resolved by #662 / https://github.com/stacks-network/stacks-blockchain/pull/2906.

Then there's a second issue with the specific endpoint mentioned by @wileyj -- looks like just a sql query missing an ORDER BY clause. This is an easy fix, but likely not going to fully solve the issue until the above issue is fixed.

**Comment by wileyj** [comment] 2022-02-02 15:39
Thanks! this isn't affecting *me* directly, but another group who's working on indexing the api data (i'm just the middleman here). I'll pass the info along

**Comment by zone117x** [comment] 2022-02-09 14:13
@wileyj I think the main problem for this issue (the sql ordering bug) was actually fixed in https://github.com/hirosystems/stacks-blockchain-api/pull/933, this change went live in v2.0.0, so I think the other API instances you were comparing may have be running a previous version. Can you verify?

**Comment by wileyj** [comment] 2022-02-09 19:36
> @wileyj I think the main problem for this issue (the sql ordering bug) was actually fixed in #933, this change went live in v2.0.0, so I think the other API instances you were comparing may have be running a previous version. Can you verify?

so far looks good from my testing. I'd say good to close, if i hear something different from the indexer i'll open a new issue. 
thanks!

**Closed** 2022-02-10 02:13 UTC
Labels: P3
