### ISSUE TITLE
missing transactions in /extended/v1/address/:principal/transactions api endpoint 

### ISSUE THREAD

**Issue by caoer** [hirosystems/stacks-blockchain-api#1098] opened 2022-03-11 20:26 UTC
**Describe the bug**
We have seen there are missing transactions in the API `(stacks-blockchain-api v2.1.1 (master:d7624e13)`
The list return correct data in `stacks-blockchain-api v1.0.6 (master:887b7d61)` 

Since this API gives the total transactions amount, it is easy to compare the number of transaction does not match between two versions of the API, with both sync up to the latest block height. 

**To Reproduce**

we have extracted part of records which has affected. 
[txs_in_v1_not_v2.json.zip](https://github.com/hirosystems/stacks-blockchain-api/files/8235361/txs_in_v1_not_v2.json.zip)

the affected address are quite large, this might not be the completed list. 
[addresses_with_error.csv.zip](https://github.com/hirosystems/stacks-blockchain-api/files/8235371/addresses_with_error.csv.zip)

Because of the data inconsistency, it is not been able to upgrade to latest version. you can use following api endpoint to see correct results
```
curl "https://stacks-node-api.alexlab.co/extended/v1/address/SP02353D65T6Q4CY94E238C0MWXK3T9KD9MKHVFW/transactions"
```
yet using following command, we are seeing 1 less transaction `0x02023df888a59bc9c7dab1692e2c3048f6783f1e0f4f3c8aa961d14a8285c991`
```
curl "https://stacks-node-api.stacks.co/extended/v1/address/SP02353D65T6Q4CY94E238C0MWXK3T9KD9MKHVFW/transactions"
```
If we try to get the tx by id, we are able to get it in both end point. 

```
## Get transaction
curl "https://stacks-node-api.stacks.co/extended/v1/tx/0x02023df888a59bc9c7dab1692e2c3048f6783f1e0f4f3c8aa961d14a8285c991"
```

**Expected behavior**
return correct txs belong to the user.

**Screenshots**
not applicable

**Console log**
not applicable

**Desktop (please complete the following information):**
not applicable

**Smartphone (please complete the following information):**
not applicable

**Additional context**

**Comment by caoer** [comment] 2022-03-11 20:39
with some preliminary look up, I think this might be related to https://github.com/hirosystems/stacks-blockchain-api/pull/951 
@rafaelcr do you mind take a look about it?

**Comment by rafaelcr** [comment] 2022-03-14 02:11
Thanks for the report. This issue has been fixed in https://github.com/hirosystems/stacks-blockchain-api/pull/1074 and released in 3.0.0. We're still working on deploying this version to our environment, though, this is why you're still getting incorrect results @caoer

**Closed** 2022-03-14 02:12 UTC

**Comment by caoer** [comment] 2022-03-23 18:43
@rafaelcr I don't think the new releases has resolved the issue. please use this to check: 

```
curl "https://stacks-node-api.stacks.co/extended/v1/address/SP349J1ZTEE71M1J5D4YS0BPQCCFJ3YSNM1P8BJY4/transactions"
```
gives us total of `181` results. 
however calling the old api gives us `191` results. 

I believe we can effectively use following to check for old results'

```
WITH principal_txs AS (
    SELECT *
    FROM txs
    WHERE canonical = true
      AND microblock_canonical = true
      AND (
                sender_address = 'SP349J1ZTEE71M1J5D4YS0BPQCCFJ3YSNM1P8BJY4' OR
                token_transfer_recipient_address = 'SP349J1ZTEE71M1J5D4YS0BPQCCFJ3YSNM1P8BJY4' OR
                contract_call_contract_id = 'SP349J1ZTEE71M1J5D4YS0BPQCCFJ3YSNM1P8BJY4' OR
                smart_contract_contract_id = 'SP349J1ZTEE71M1J5D4YS0BPQCCFJ3YSNM1P8BJY4'
        )
)
select count(*)
FROM principal_txs
```

**Comment by caoer** [comment] 2022-03-23 19:21
[Archive.zip](https://github.com/hirosystems/stacks-blockchain-api/files/8335922/Archive.zip)

@rafaelcr I've attached txs which should be included in the API but it is missing.

**Comment by caoer** [comment] 2022-03-23 19:23
probably we should write a query with optimized DB to build a table of txs and match the count number with previous query to check if the data is correct?

**Comment by rafaelcr** [comment] 2022-03-23 19:33
@caoer thanks for following up. I believe, however, that what you describe is a duplicate of this issue: https://github.com/hirosystems/stacks-blockchain-api/issues/1119

**Comment by caoer** [comment] 2022-03-23 19:44
@rafaelcr thanks for reply us quickly. I just come across #1119 while looking over issues list. let me reply on that issue instead.
