### ISSUE TITLE
registered .id.stx is not returned by the API

### ISSUE THREAD

**Issue by pradel** [hirosystems/stacks-blockchain-api#1551] opened 2023-02-12 10:48 UTC
**Describe the bug**

The username `project_indigo.id.stx` is not being returned by the stacks blockchain API but by the registrar API.

When calling the Stacks API to get information linked to this name, https://stacks-node-api.mainnet.stacks.co/v1/names/project_indigo.id.stx. We can see that we are being redirected to the registrar API https://registrar.stacks.co/v1/names/project_indigo.id.stx.
The name-update call has already been confirmed in the blockchain with this transaction https://explorer.stacks.co/txid/0xa6223f468556e9f2206120bc59799c2dae728ae3638b88b86f8df5118a1d250b?chain=mainnet. When a name-update call is made and confirmed, the blockchain API should return the name information without redirecting the call to the registrar.

**Expected behavior**

The Stacks node API should return the record directly and not redirect the request to the registrar.

**Comment by rafaelcr** [comment] 2023-02-14 16:23
Since this is a subdomain, I believe this issue is a duplicate of https://github.com/hirosystems/stacks-blockchain-api/issues/1269

**Comment by pradel** [comment] 2023-03-09 10:20
Yes you are right 👍

**Closed** 2023-03-09 10:20 UTC
