### ISSUE TITLE
subscribeBlocks and subscribeMempool don't work after 9 hours

### ISSUE THREAD

**Issue by dhwndud408** [hirosystems/stacks-blockchain-api#2173] opened 2024-11-20 04:24 UTC
Hi! dev teams.

I am making code with your api.
Here is my computer info.
Mac OS Sonoma14.4
Node 18.19.1
NPM 10.2.4
API version: 8.2.0

Here is the typescript code
```
import * as stacks from '@stacks/blockchain-api-client';
const socketUrl = "https://api.mainnet.hiro.so";
const socket = new stacks.StacksApiSocketClient({ url: socketUrl });

let client = await stacks.connectWebSocketClient('wss://api.mainnet.hiro.so/');


sub = await socket.subscribeBlocks((event) => {
   console.log(event)
}
sub = await socket.subscribeBlocks((event) => {
console.log(event)
}
```

After about 6~9 hours, the websocket stops.

I also see the this report.
https://github.com/hirosystems/stacks-blockchain-api/issues/1885

The admin said it was resolved on above link, but it seems the issue has resurfaced with the Nakamoto update.

**Comment by zone117x** [comment] 2024-11-20 09:46
Closing as a duplicate of https://github.com/hirosystems/stacks-blockchain-api/issues/2146

**Closed by zone117x** 2024-11-20 09:46 UTC
