### ISSUE TITLE
Stacks API reporting pending transactions much older than 256 BTC blocks

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/stacks-blockchain-api#898] opened 2021-12-11 11:02 UTC
**Describe the bug**
The Stacks API is reporting pending transactions much older than 256 blocks. I would not expect this. 

**To Reproduce**
1. Go to https://haystack.tools/mempool
2. Click on contract calls
3. Scroll down to oldest transactions
4. See error: _2 month old transactions_

**Expected behavior**
I would expect to see transactions with an age of 256 BTC blocks (~2 days) at most because after that they are dropped from the mempool

**Screenshots**
![image](https://user-images.githubusercontent.com/33360391/145674085-3e00b3ea-58e0-4bb3-9f4d-7377d05d30ff.png)

**Console log**
Example of a tx id that is shown in https://haystack.tools/mempool but does not show on the Explorer.stacks.co

{
  tx_id: "0x338b0be769b3bb5597b0bb3911ee92600f81ef205dac5c758d0d384645dbbbf0",
  nonce: 55,
  fee_rate: "330000",
  sender_address: "SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S",
  sponsored: false,
  post_condition_mode: "deny",
  post_conditions: [ ],
  anchor_mode: "any",
  tx_status: "pending",
  receipt_time: 1635875104,
  receipt_time_iso: "2021-11-02T17:45:04.000Z",
  tx_type: "contract_call",
  contract_call: {
  contract_id: "SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.testing-liquidity",
  function_name: "claim",
  function_signature: ""
},

**Additional context**
The dashboards ([1](https://stacksdata.info/#mempool) and [2](https://haystack.tools/mempool)) currently revealing these really old pending transactions could drop them based on their age but Petter and I think it may be better to look closer at the root cause so it may be prevented completely. 

The average time of transactions in the mempool reported here is probably mostly influenced by these transactions that cannot be mined (nonce issue related perhaps?)
![image](https://user-images.githubusercontent.com/33360391/145674138-81398c0a-fb34-439c-919b-234f9decfda6.png)

**Comment by zone117x** [comment] 2021-12-14 16:02
Under normal operations, txs are dropped from the mempool once the API receives a [`POST /drop_mempool_tx`](https://github.com/blockstack/stacks-blockchain/blob/master/docs/event-dispatcher.md#post-drop_mempool_tx) event from the stacks-node. 

Seems like there's several reasons there might not be a perfect 1-1 between received mempool txs and the drop events. The API could flag these older mempool txs as dropped itself, probably in the same routine that ingests new blocks. We'd just want to be sure we can hardcode the 256 block constant safely (e.g. assume this won't ever change in the stacks-node and cause discrepancies).

**Comment by zone117x** [comment] 2021-12-14 16:22
We should also add some info to docs around API mempool view being different than mempool view of any given stacks-node

**Comment by MHassanTariq** [comment] 2022-01-17 09:13
@zone117x the mempool txs are not assigned to any block. Therefore, there is not any `block_hash` associated with a [mempool_tx](https://github.com/hirosystems/stacks-blockchain-api/blob/develop/src/migrations/1591291822107_mempool_txs.ts). How are we going to define which mempool txs are to be dropped when ingesting a new block? Are we converting `block_height of the new block, minus 256`  to time (i.e. considering each block is created in 10 minutes) and then dropping all mempool txs before that time?

**Comment by rafaelcr** [comment] 2022-03-01 17:57
Closing as a duplicate of https://github.com/hirosystems/stacks-blockchain-api/issues/1059

**Closed by rafaelcr** 2022-03-01 17:57 UTC
Labels: P3
