### ISSUE TITLE
Transactions occasionally unavailable after their IDs returned to app by wallet upon broadcast

### ISSUE THREAD

**Issue by bilalanees98** [hirosystems/stacks-blockchain-api#1354] opened 2022-10-06 06:31 UTC
The issue that users have been facing on btc.us is that they make e.g. a name-preorder and that works fine. When they make the name-register call the contract call opens up and when they confirm the contract call closes. The application receives a txid that it stores on gaia and starts monitoring. However, this txid does not show up on the wallet, the explorer and the api, essentially it doesn’t get broadcasted. 
A more recent example of this issue that was shared by a user:
![btc us issue](https://user-images.githubusercontent.com/62988673/194229880-6768891a-fe57-4219-8560-8230ed3dace0.png)
![hiro wallet issue](https://user-images.githubusercontent.com/62988673/194229893-9b942bfe-8dcc-44e8-bca2-755b1819bc9d.png)
txid link: https://explorer.stacks.co/txid/3e1930b21db6ff6d16db647c114b3241ca6b3a2249c36a28bdba32bb746764f6?chain=mainnet

All the dapp checks for is the txId that is returned in an object. And it is important to note that is a rare case and does not happened often. Another possible important piece of information is that the users who face this are users that have a lot of addresses in their wallet.
To me there are two possibilities:

1- The broadcast fails and the wallet returns the txid in the broadcastFailedResponse as the txId. This is picked up by the application and then used. 
For this I have tried out the test demo app (https://github.com/hirosystems/stacks-wallet-web/pull/2705) that was shared with me. I tried multiple cases and the results are as follows:

- Fudging the fn argument types passed to the contract call - picked up by Hiro wallet and a warning/error is displayed (expected behavior)
- Setting a bad nonce value - picked up by Hiro wallet and a warning/error is displayed (expected behavior)
So I have been unable to replicate the issue. I am not sure if these issues are those that are picked up by the wallet before an attempted broadcast or after them.

2- The transaction itself is valid and broadcast-able but it doesn’t end up up being broadcasted by the wallet.

Either way I think we need to figure out the cause of the issue and fix it, because this is definitely impacting users.

A quick fix for dapps could be to check the txid received as a result and to see whether it has been broadcast. imo, This would only work if the tx is broadcast immediately by the wallet.  Do you think this could potentially be a fix?

Seems to me that every txid that is returned to the dapp should be a valid broadcasted txid, if it isn’t broadcasted, an error value should be thrown. And we need to standardise these responses across all wallets.

**Comment by markmhx** [comment] 2022-10-13 08:11
I've transferred this to the API repository since it appears to be an API- (or perhaps node-) based issue, seeing that the wallet is only returning IDs for transactions to apps that it has indeed broadcasted.

@rafaelcr do you feel you have the contextual information you all might need to investigate this, or should @bilalanees98 or we on the wallet team help with more input?

**Comment by diwakergupta** [comment] 2022-10-13 15:00
Do we have any data (logs etc) from the wallet that can let us definitively conclude that a transaction _was_ successfully broadcast and then still didn't show up in the API? I don't see the txid `3e1930b21db6ff6d16db647c114b3241ca6b3a2249c36a28bdba32bb746764f6` in our mock miner logs FWIW. @rafaelcr can we check the API logs, or the node pool the API uses as well?

In general the API can't know what transactions have been broadcast by any given client -- that's state that clients have to track. Even _if_ the tx was successfully delivered to a node, I think there might still be situations where it doesn't propagate to the network (e.g. the node that received it crashes before it can broadcast it to peers) -- this is something that would have to be retried on the client end, no way for the API to handle such cases.

**Comment by kyranjamie** [comment] 2022-10-14 08:26
> Do we have any data (logs etc) from the wallet that can let us definitively conclude that a transaction was successfully broadcast and then still didn't show up in the API

We don't track this info. Tracking is opt-in, so even if we did, the user would have had to given permissions.

**Comment by rafaelcr** [comment] 2022-10-14 15:40
> @rafaelcr can we check the API logs

Yep, I just checked in the API both in our prod env and a local one I have here and neither of those have that transaction. I don't believe the tx was successfully broadcasted.

**Comment by bilalanees98** [comment] 2022-10-18 08:31
I am trying to find a workaround for this issue.

The client-side will rely on the stacks-api for tx related info. Is it safe to assume that a txid returned from the wallet that is "not_found" on the API is a transaction that has not been broadcast. Or is there going to be a time period during which the transaction broadcast (apparently) from the wallet (and returned to the dapp) will be "not_found" before changing into "found" (or in the mempool).
Does this translate into "if transaction is 'not_found' for X time (e.g. 10 mins), allow the user to try again"?

cc - @rafaelcr @kyranjamie

**Comment by rafaelcr** [comment] 2022-10-19 16:42
@bilalanees98 
> Is it safe to assume that a txid returned from the wallet that is "not_found" on the API is a transaction that has not been broadcast. Or is there going to be a time period during which the transaction broadcast (apparently) from the wallet (and returned to the dapp) will be "not_found" before changing into "found" (or in the mempool).

The latter is true. stacks.js may return a transaction id that was sent to a node and confirmed, but there will definitely be a time gap for that tx to reach our APIs on mempool messages. It's tough to tell how long it can take. Sometimes we never receive the mempool message but we do get that tx when a subsequent block or microblock comes.

In this case I would suggest either calling the API a few seconds after to confirm the tx exists in the mempool or better yet, subscribing to that `tx_id` in the API's websockets to get an update when we receive it.

**Comment by markmhx** [comment] 2022-11-22 13:48
@bilalanees98 has this issue been occurring recently in your experience?

**Comment by bilalanees98** [comment] 2022-11-22 14:04
@markmhx this has not been reported by any users recently. Additionally, I have deployed a counter measure for this now.
If a tx is not found for 1 min, the app will prompt the user to try again for the particular tx.

**Closed** 2022-11-22 15:59 UTC
Labels: bug, P2, BNS
