### ISSUE TITLE
`last_txid` showing as `[Object object]` in `/v1/names`

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1010] opened 2022-01-27 21:38 UTC
Example: https://registrar.stacks.co/v1/names/testtesttest101.id.stx
```json
{
  "blockchain": "stacks",
  "status": "submitted_subdomain",
  "last_txid": "[object Object]",
  "zonefile": "$ORIGIN testtesttest101.id.stx\n$TTL 3600\n_http._tcp\tIN\tURI\t10\t1\t\"https://gaia.blockstack.org/hub/17Jw7GtY2twdd9ym7pWZQPZALeSXDtCQYL/profile.json\"\n\n",
  "address": "SP2DVAFYG67H29CBFHH2PWJ2RSTZD8AFM5KEC62VS",
  "zonefile_hash": "2e83bb80dbeb13179253fec281f4ea0c20723e93"
}
```
Might be related to the code that inserts those domain names into the database https://github.com/hirosystems/stacks-blockchain-api/blob/master/src/datastore/postgres-store.ts#L4272

**Comment by asimm241** [comment] 2022-02-09 07:11
@rafaelcr  The problem is on the registrar repo, API redirects it to the registrar when it does not find it locally see here : 
https://github.com/hirosystems/stacks-blockchain-api/blob/cd51c1bd26e2614731413ceff2c1f5c95c4aa0a8/src/api/routes/bns/names.ts#L96

The name is not actually registered as you can see from this endpoint: https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP2DVAFYG67H29CBFHH2PWJ2RSTZD8AFM5KEC62VS

The registrar is returning name info from its own DB.  We should close this issue on the API side.

**Comment by zone117x** [comment] 2022-02-09 15:50
Thanks for debugging @asimm241!

**Closed by zone117x** 2022-02-09 15:50 UTC
Labels: bug, BNS, tt
