### ISSUE TITLE
Improve mempool data

### ISSUE THREAD

**Issue by obycode** [hirosystems/stacks-blockchain-api#1428] opened 2022-11-09 19:23 UTC
Recent work on the stacks node (e.g. https://github.com/stacks-network/stacks-blockchain/pull/3337, https://github.com/stacks-network/stacks-blockchain/pull/3349) exposes better sources for the mempool data. This is a generic issue to discuss how the API node is currently computing mempool information and how we can improve this data using the new techniques. Various ecosystem entities are relying on these endpoints.

Related endpoints:
* https://docs.hiro.so/api#tag/Rosetta/operation/rosetta_mempool
* https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list

**Comment by zone117x** [comment] 2022-11-10 12:29
It looks like there's a few approaches to improve mempool data for public consumption:
* Expose the mempool data that folks are interested in through the stacks-node RPC endpoints.
* Expose those stacks-node mempool prometheus metrics to the public in some fashion.
* Add the improved stacks-node mempool data to the event-stream, in which case the API could store that in postgres and return in an API endpoint.

The API endpoints you mentioned are currently returning a view of the mempool based on the `new_mempool_tx`, `drop_mempool_tx`, and `new_microblocks` events. Note that these events are "lossy" / unreliable due to race-conditions in the stacks-node. This causes events to sometimes be emitted out-of-order with respect to each other, or out-of-order in respect to the `new_block` event (which is generally the only event that is a reliable source-of-truth). In some of these situations, especially when there are also anchor-block and/or microblock re-orgs happening, the API does not have accurate enough data from the stacks-node to ensure its view of the mempool is 100% correct. 

There are known issues where the API can sometimes return a mined tx with correct data, but also have the same tx incorrectly reported as still in the mempool. There are several areas in the API's re-org handling code to try to prevent this situation, however, due to the complexity of handling anchor-block and microblock re-orgs _at the same time_ as trying to handle buggy / out-of-order data from the stacks-node, we end up with a garbage in, garbage out scenario. 

In the past when trying to resolve these discrepancies in the API, we end up adding more postgres disk/computational overhead to the already expensive process of ingesting event data, and typically also introduce regressions. For example, we fix one scenario of a tx being inaccurately reported as still in the mempool, which inadvertently causes a bug where a tx can end up being reported as completely missing from both the mempool view & the mined tx view (e.g. after some inscrutable series of out-of-order or missing events during a series of re-org events).

When we've previously discussed these issues with the event-emitter behavior, there's a general consensus that it should not be so difficult for an event-observer (like the API and any others) to build accurate views of the blockchain data, and that the stacks-node ought to fix issues around those race-conditions and/or whatever else. However, that's seemingly a difficult task, so for that reason I recommend one of the 3 approaches I first mentioned.

**Comment by wileyj** [comment] 2023-02-13 19:51
some new info that came up recently - 
a confirmed tx `0x815c32ebe2188a47bf9e9d5b387b6b9f5cd30a4a5fca5d13086fa7efd235ded5` 
```bash
➭ curl -sL https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x815c32ebe2188a47bf9e9d5b387b6b9f5cd30a4a5fca5d13086fa7efd235ded5 | jq -r  '.tx_status,.nonce,.burn_block_time_iso'
success
8522
2023-02-13T02:00:34.000Z
```

was also still listed in the `/extended/v1/tx/mempool` endpoint for far longer than expected:
```bash
➭ curl -sL https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool\?sender_address\=SP34EBMKMRR6SXX65GRKJ1FHEXV7AGHJ2D8ASQ5M3 | jq -r '.results | .[4]' | jq '.tx_status,.nonce,.receipt_time_iso'

"pending"
8522
"2023-02-13T01:47:38.000Z"
```

**Comment by 0xbabo** [comment] 2023-02-14 20:00
This is causing faulty stats at `/extended/v1/tx/mempool/stats` endpoint and in turn bad historical data at https://stacksonchain.com (refer to [my dashboard here](https://stacksonchain.com/dashboards/Gas%20Fees%20%26%20Mempool%20%40%20Babo/186)). 

<img width="1327" alt="Screenshot 2023-02-14 at 11 53 39 AM" src="https://user-images.githubusercontent.com/110633279/218847050-d70fe0e1-0ac1-4eba-8f20-8536b4f243ab.png">

**Comment by zone117x** [comment] 2023-02-24 11:59
Most of the issues discussed here should be fixed by https://github.com/hirosystems/stacks-blockchain-api/pull/1561

Further improvements to mempool data will likely need to be implemented in the stacks-node.

I'm going to close this issue for now. Please let comment here if anyone continues to see mempool related problems.

**Closed by zone117x** 2023-02-24 11:59 UTC
