### ISSUE TITLE
Websockets: Unable to received testnet events

### ISSUE THREAD

**Issue by zeeshanakram27** [hirosystems/stacks-blockchain-api#785] opened 2021-10-01 13:02 UTC
## Unable to capture events of Testnet

I am observing the contract on mocknet using following piece of code. We are using [@stacks/blockchain-api-client](https://blockstack.github.io/stacks-blockchain-api/client/index.html)

```
async function subscriber() {
  const STACKS_CORE_API_WS_URL = 'ws://localhost:3999';
  const client = await connectWebSocketClient(STACKS_CORE_API_WS_URL);
  client.subscribeAddressTransactions(
    'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.oracle',
    event => {
      console.log('event', event);
    }
  );
}
```

Its working fine, and we are getting events like

   ```
 {
  address: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.oracle',
  tx_id: '0x09141bb7dd97fae2bf530f9b1adb087d052cd854e2ed5e5ce398fee6d303c7f4',
  tx_status: 'success',
  tx_type: 'contract_call'
}
```

However, for the testnet I am only updating this url. `const STACKS_CORE_API_WS_URL = 'wss://stacks-node-api.testnet.stacks.co/'`

For observing testnet events, our code looks like following:

```
async function subscriber() {
 const STACKS_CORE_API_WS_URL = 'wss://stacks-node-api.testnet.stacks.co/'
  const client = await connectWebSocketClient(STACKS_CORE_API_WS_URL);
  client.subscribeAddressTransactions(
    'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.oracle',
    event => {
      console.log('event', event);
    }
  );
}
```

But we did not receive any events.
In order to create a transaction we are using this code:
```

export function createDirectRequestTxOptions(network: StacksNetwork, mockRequest: any) {
  const consumerAddress = 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM';
  const assetInfo = createAssetInfo(
    'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM',
    'stxlink-token',
    'stxlink-token'
  );
  const postCondition = createFungiblePostCondition(
    'STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6',
    FungibleConditionCode.Equal,
    new BigNum(1),
    assetInfo
  );
  const jobIdBuff = bufferToHexPrefixString(Buffer.from(String(mockRequest['job-id'])));
  const paramBuff = bufferToHexPrefixString(Buffer.from(JSON.stringify(mockRequest.params)));
  const senderPrincipalBuff = bufferToHexPrefixString(
    Buffer.from('STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6')
  );
  const oracle = {
    address: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM',
    name: 'oracle',
  };
  const txOptions = {
    contractAddress: consumerAddress,
    contractName: 'direct-request',
    functionName: 'create-request',
    functionArgs: [
      bufferCVFromString(jobIdBuff),
      bufferCVFromString(senderPrincipalBuff),
      bufferCVFromString(paramBuff),
      contractPrincipalCV(oracle.address, oracle.name),
      contractPrincipalCV('ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM', 'direct-request'),
      contractPrincipalCV('ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM', 'direct-request'),
    ],
    senderKey: '753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601',
    validateWithAbi: true,
    network,
    fee: new BigNum(200000),
    postConditions: [postCondition],
    anchorMode: 1,
  };
  return txOptions;
}
```

```
router.get('/consumer-test', async (req, res) => {
    const network = new StacksTestnet();
    const mockRequest = {
      id: 1,
      type: 'get',
      'job-id': 'e2e87d802508402a85224d62a7ff4289',
      params: {
        get: 'https://min-api.cryptocompare.com/data/price?fsym=STX&tsyms=USD',
        path: 'USD',
      },
    };
    const txOptions = createDirectRequestTxOptions(network, mockRequest);
    try {
      const transaction = await makeContractCall(txOptions);
      const broadcastResult = await broadcastTransaction(transaction, network);
      const txRejected = broadcastResult as TxBroadcastResultRejected;
      const error = txRejected.error;
      if (error) {
        res
          .status(400)
          .json({ msg: error + ' with reason: ' + txRejected.reason })
          .end();
      }
      res.status(200).json({
        txid: transaction.txid(),
      });
    } catch (err: any) {
      res.status(400).json({ msg: err.message });
    }
  });
```
## Steps To Reproduce

To reproduce use above Testnet's piece of code

## Expected behavior

Should capture events of contracts deployed on testnet.

**Comment by rafaelcr** [comment] 2021-10-01 14:41
@zeeshanakram27 could you try running the same test scenarios but using the socket-io client library instead? I'd like to test if the problem is specific to the WebSockets code.

This is an example of how to do that:
```typescript
import { io } from "socket.io-client";
import * as stacks from '@stacks/blockchain-api-client';

const socketUrl = "https://stacks-node-api.testnet.stacks.co/";
const socket = io(socketUrl, {query: {
  subscriptions: Array.from(new Set([
    'address-transaction: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.contract-name',
  ])).join(','),
}});
const sc = new stacks.StacksApiSocketClient(socket);
```

**Comment by noumanahmads** [comment] 2021-10-01 15:29
@rafaelcr 
I have used your code and added this:  `sc.logEvents()` . 
It did logged the event for me : 

```
ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.oracle {
  tx: {
    tx_id: '0x8a3be767e6c99f94d42bdb72a6600a900af84e7e1e22b53b14e0882827d7e8d5',
    nonce: 25,
    fee_rate: '1000000',
    sender_address: 'STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6',
    sponsored: false,
    post_condition_mode: 'deny',
    post_conditions: [ [Object] ],
    anchor_mode: 'on_chain_only',
    is_unanchored: false,
    block_hash: '0x309eca386a2fe508ea411dd230757842394ed39ff097fd6cf1ab56682c4f53d7',
    parent_block_hash: '0xa517f0a324591e771be32a6f528a6d597ebca7e56fa6ca39d5bb417e726b50ab',
    block_height: 13811,
    burn_block_time: 1633101600,
    burn_block_time_iso: '2021-10-01T15:20:00.000Z',
    parent_burn_block_time: 1633100350,
    parent_burn_block_time_iso: '2021-10-01T14:59:10.000Z',
    canonical: true,
    tx_index: 1,
    tx_status: 'success',
    tx_result: { hex: '0x0703', repr: '(ok true)' },
    microblock_hash: '',
    microblock_sequence: 2147483647,
    microblock_canonical: true,
    event_count: 2,
    events: [],
    execution_cost_read_count: 24,
    execution_cost_read_length: 23368,
    execution_cost_runtime: 36422675,
    execution_cost_write_count: 4,
    execution_cost_write_length: 125,
    tx_type: 'contract_call',
    contract_call: {
      contract_id: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.direct-request',
      function_name: 'create-request',
      function_signature: '',
      function_args: [Array]
    }
  },
  stx_sent: '0',
  stx_received: '0',
  stx_transfers: []
}

```

**Comment by agraebe** [comment] 2021-10-04 19:29
I noticed that you used `wss://stacks-node-api.testnet.stacks.co/` as the socket url in your original code @noumanahmad001. @rafaelcr used `https` for socketio (maybe the protocol doesn't have to be specified in this case). 

However, [one docs page](https://docs.stacks.co/build-apps/examples/public-registry#step-3-connect-to-web-socket) and [this comment in the sample code](https://blockstack.github.io/stacks-blockchain-api/client/index.html#usage) specifies `ws://` as the protocol, so I wonder if the original code isn't working because of that? Did you try `ws` or `https`?

**Comment by zone117x** [comment] 2021-10-05 14:25
> I noticed that you used `wss://stacks-node-api.testnet.stacks.co/` as the socket url in your original code @noumanahmad001. @rafaelcr used `https` for socketio (maybe the protocol doesn't have to be specified in this case).
> 
> However, [one docs page](https://docs.stacks.co/build-apps/examples/public-registry#step-3-connect-to-web-socket) and [this comment in the sample code](https://blockstack.github.io/stacks-blockchain-api/client/index.html#usage) specifies `ws://` as the protocol, so I wonder if the original code isn't working because of that? Did you try `ws` or `https`?

Any websocket client lib will ultimately have to translate `http(s)://` to `ws(s)://`, otherwise the `WebSocket` constructor will throw. Most libs do this conversion for you, so that shouldn't be an issue.

**Comment by noumanahmads** [comment] 2021-10-07 06:38
> After some digging, the most likely explanation for this issue so far is an infrastructure configuration that is preventing sessions from staying alive and receiving messages correctly through WebSockets (even on testnet). @CharlieC3 is going to help me to create a new config this week that could solve the issue. Stay tuned.

Thank @rafaelcr

**Comment by rafaelcr** [comment] 2022-01-21 16:58
This has been fixed with the latest testnet upgrade

**Closed by rafaelcr** 2022-01-21 16:58 UTC
Labels: bug, testnet, sockets
